const baseUrl = 'http://127.0.0.1:8080';
let token = '';
let postId = '';
let commentId = '';

const runTests = async () => {
    console.log("🚀 Starting Route Tests...\n");

    // Helper function to make requests and print formatted output
    const makeRequest = async (name, url, method, body, auth = true) => {
        const headers = {};
        if (auth && token) headers['Authorization'] = `Bearer ${token}`;
        
        let reqBody = body;
        // If it's not FormData and it exists, format as JSON
        if (!(body instanceof FormData) && body) {
            headers['Content-Type'] = 'application/json';
            reqBody = JSON.stringify(body);
        }

        console.log(`Testing: [${method}] ${url} (${name})`);
        
        try {
            const response = await fetch(`${baseUrl}${url}`, {
                method,
                headers,
                body: reqBody
            });
            const data = await response.json().catch(() => null);
            const isOk = response.status >= 200 && response.status < 300;
            console.log(`  --> Status: ${response.status} ${isOk ? '✅' : '❌'}`);
            if (!isOk && data) console.log(`  --> Error:`, data);
            return { status: response.status, data };
        } catch (e) {
            console.error('  --> ❌ Request failed completely:', e.message);
            return { status: 500, data: null };
        }
    };

    // Use Date.now() to ensure we create a brand new user every time we run the script
    const unique = Date.now();
    
    // 1. Register
    await makeRequest('Register', '/register', 'POST', {
        name: 'Test Robot',
        username: `robot_${unique}`,
        email: `robot${unique}@example.com`,
        password: 'password123'
    }, false);

    // 2. Login
    const loginRes = await makeRequest('Login', '/login', 'POST', {
        email: `robot${unique}@example.com`,
        password: 'password123'
    }, false);
    
    if(loginRes.data && loginRes.data.token) {
        token = loginRes.data.token;
        console.log("  --> 🔑 Got Auth Token! Moving to protected routes...\n");
    } else {
        console.log("❌ Failed to get token. Aborting rest of the tests.");
        return;
    }

    // 3. User Profile
    await makeRequest('Get User Profile', '/get_user_profile', 'GET');

    // 4. Update Profile Data
    await makeRequest('Update Profile Data', '/update_profile_data', 'POST', {
        newProfileData: { bio: "Beep boop! I am an automated test robot." }
    });

    // 5. Search Users (Using the new regex search we built!)
    await makeRequest('Search Users', `/user/search?query=robot_${unique}`, 'GET');

    // 6. Create Post
    const formData = new FormData();
    formData.append('body', 'This is an automated test post generated by the script!');
    await makeRequest('Create Post', '/upload_post', 'POST', formData);
    
    // Give the DB a split second to save the post
    await new Promise(res => setTimeout(res, 500));

    // 7. Get User Posts (to grab the Post ID)
    const postsRes = await makeRequest('Get User Posts', '/user/posts', 'GET');
    if (postsRes.data && postsRes.data.length > 0) {
        postId = postsRes.data[0]._id;
        
        // 8. Like Post
        await makeRequest('Like Post', '/post/like', 'POST', { postId });

        // 9. Comment on Post
        await makeRequest('Comment on Post', '/post/comment', 'POST', { post_id: postId, comment: 'Automated comment!' });

        // 10. Get Comments
        const commentsRes = await makeRequest('Get All Comments', `/post/all_comments?post_id=${postId}`, 'GET');
        if (commentsRes.data && commentsRes.data.length > 0) {
            commentId = commentsRes.data[0]._id;
            
            // 11. Delete Comment
            await makeRequest('Delete Comment', '/post/delete_comment', 'POST', { post_id: postId, commentId });
        }

        // 12. Feed
        await makeRequest('Get Feed', '/feed', 'GET');

        // 13. Search Posts (Elasticsearch)
        await makeRequest('Search Posts (Elasticsearch)', '/search_posts?query=automated', 'GET', null, false);

        // 14. Delete Post
        await makeRequest('Delete Post', '/delete_post', 'POST', { postId });
    } else {
        console.log("❌ Failed to retrieve posts. Skipping post-interaction tests.");
    }

    // 15. Logout
    await makeRequest('Logout', '/logout', 'POST');

    console.log("\n🎉 All tests completed!");
};

runTests();
